"""Initial migration

Revision ID: daa7fa3fcabe
Revises: 9b18e8cb7d2c
Create Date: 2024-12-23 21:50:25.354437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa7fa3fcabe'
down_revision: Union[str, None] = '9b18e8cb7d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
